uint8 PICK=1
uint8 PLACE=2

# request
geometry_msgs/Pose destination_pose
geometry_msgs/Pose gripper_station_pose
uint8 pick_place
int8 tray_id # if -1 no tray
int8 part_type  # if -1 no part else battery=ariac_msg.msg.part, sensor, etc.
---
# response
bool success
string message
